import * as THREE from "three";
import { GLTF } from "three-stdlib";

export type GLTFResult = GLTF & {
  nodes: {
    Case_Glass: THREE.Mesh
    Screen_2: THREE.Mesh
    Screen_3: THREE.Mesh
    Screen_1: THREE.Mesh
    ['Fish-Glass']: THREE.Mesh
    ['Fish-Water']: THREE.Mesh
    ['Water-Mug']: THREE.Mesh
    ['Poster-1']: THREE.Mesh
    Frame_1: THREE.Mesh
    Frame_2: THREE.Mesh
    Frame_3: THREE.Mesh
    Hour_Hand_First: THREE.Mesh
    Minute_Hand_First: THREE.Mesh
    Chair_Second_Raycaster_Hover: THREE.Mesh
    Fish_Second_Hover_Raycaster: THREE.Mesh
    Dot_1_Raycaster_Hover_Third: THREE.Mesh
    Dot_2_Raycaster_Hover_Third: THREE.Mesh
    Dot_3_Raycaster_Hover_Third: THREE.Mesh
    Name_Letter_1_Third_Raycaster_Hover: THREE.Mesh
    Name_Letter_2_Third_Raycaster_Hover: THREE.Mesh
    Name_Letter_3_Third_Raycaster_Hover: THREE.Mesh
    Name_Letter_4_Third_Raycaster_Hover: THREE.Mesh
    Name_Letter_5_Third_Raycaster_Hover: THREE.Mesh
    Name_Letter_6_Third_Raycaster_Hover: THREE.Mesh
    Name_Letter_7_Third_Raycaster_Hover: THREE.Mesh
    Name_Letter_8_Third_Raycaster_Hover: THREE.Mesh
    Name_Letter_9_Third_Raycaster_Hover: THREE.Mesh
    Name_Letter_10_Third_Raycaster_Hover: THREE.Mesh
    Name_Letter_11_Third_Raycaster_Hover: THREE.Mesh
    Name_Letter_12_Third_Raycaster_Hover: THREE.Mesh
    Rock_1_Third_Raycaster_Hover: THREE.Mesh
    Rock_2_Third_Raycaster_Hover: THREE.Mesh
    Rock_3_Third_Raycaster_Hover: THREE.Mesh
    Rock_4_Third_Raycaster_Hover: THREE.Mesh
    Rock_5_Third_Raycaster_Hover: THREE.Mesh
    Rock_6_Third_Raycaster_Hover: THREE.Mesh
    Rock_7_Third_Raycaster_Hover: THREE.Mesh
    Seaweed_1_Hover_Third_Raycaster: THREE.Mesh
    Seaweed_2_Hover_Third_Raycaster: THREE.Mesh
    Seaweed_3_Hover_Third_Raycaster: THREE.Mesh
    Seaweed_4_Hover_Third_Raycaster: THREE.Mesh
    Seaweed_5_Hover_Third_Raycaster: THREE.Mesh
    Seaweed_6_Hover_Third_Raycaster: THREE.Mesh
    Seaweed_7_Hover_Third_Raycaster: THREE.Mesh
    Seaweed_8_Hover_Third_Raycaster: THREE.Mesh
    Seaweed_9_Hover_Third_Raycaster: THREE.Mesh
    Seaweed_10_Hover_Third_Raycaster: THREE.Mesh
    Seaweed_11_Hover_Third_Raycaster: THREE.Mesh
    Seaweed_12_Hover_Third_Raycaster: THREE.Mesh
    Hanging_Plank_1_Third: THREE.Mesh
    ['A#1_Third']: THREE.Mesh
    ['A#2_Third']: THREE.Mesh
    A1_Third: THREE.Mesh
    A2_Third: THREE.Mesh
    B1_Third: THREE.Mesh
    B2_Third: THREE.Mesh
    ['C#1_Third']: THREE.Mesh
    ['C#2_Third']: THREE.Mesh
    C1_Third: THREE.Mesh
    C2_Third: THREE.Mesh
    ['D#1_Third']: THREE.Mesh
    ['D#2_Third']: THREE.Mesh
    D1_Third: THREE.Mesh
    D2_Third: THREE.Mesh
    E1_Third: THREE.Mesh
    E2_Third: THREE.Mesh
    ['F#1_Third']: THREE.Mesh
    ['F#2_Third']: THREE.Mesh
    F1_Third: THREE.Mesh
    F2_Third: THREE.Mesh
    ['G#1_Third']: THREE.Mesh
    ['G#2_Third']: THREE.Mesh
    G1_Third: THREE.Mesh
    G2_Third: THREE.Mesh
    Bird_Father_Fourth_Raycaster_Hover: THREE.Mesh
    Bird_Son_Fourth_Raycaster_Hover: THREE.Mesh
    Box_1_Hover_Fourth_Raycaster: THREE.Mesh
    Box_2_Hover_Fourth_Raycaster: THREE.Mesh
    Box_3_Hover_Fourth_Raycaster: THREE.Mesh
    Cam_Fourth_Raycaster_Hover: THREE.Mesh
    Computer_Fan_1_Fourth_Raycaster: THREE.Mesh
    Computer_Fan_2_Fourth_Raycaster: THREE.Mesh
    Computer_Fan_3_Fourth_Raycaster: THREE.Mesh
    Computer_Fan_4_Fourth_Raycaster: THREE.Mesh
    Computer_Fan_5_Fourth_Raycaster: THREE.Mesh
    Duck_Father_Fourth_Hover_Raycaster: THREE.Mesh
    Duck_Son_Fourth_Hover_Raycaster: THREE.Mesh
    Keyboard_Raycaster_Hover_Fourth: THREE.Mesh
    Kitten_Raycaster_Hover_Fourth: THREE.Mesh
    Puppy_Raycaster_Hover_Fourth: THREE.Mesh
    Slipper_1_Fourth_Hover_Raycaster: THREE.Mesh
    Slipper_2_Fourth_Hover_Raycaster: THREE.Mesh
    Bulb_1_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_2_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_3_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_4_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_5_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_6_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_7_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_8_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_9_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bear_Father_Fourth_Hover_Raycaster: THREE.Mesh
    Bear_Son_Fourth_Hover_Raycaster: THREE.Mesh
    Boba_Plushie_Fourth_Raycaster_Hover: THREE.Mesh
    Coffee_Mug_Fourth_Raycaster_Hover: THREE.Mesh
    Egg_1_Fourth_Hover_Raycaster: THREE.Mesh
    Egg_2_Fourth_Hover_Raycaster: THREE.Mesh
    Egg_3_Fourth_Hover_Raycaster: THREE.Mesh
    Evee_Fourth_Raycaster_Hover: THREE.Mesh
    Flower_Basket_Raycaster_Hover_Fourth: THREE.Mesh
    GitHub_Fourth_Raycaster_Pointer_Hover: THREE.Mesh
    Lamp_Fourth_Hover_Raycaster: THREE.Mesh
    LinkedIn_Fourth_Raycaster_Pointer_Hover: THREE.Mesh
    Mouth_Raycaster_Hover_Fourth: THREE.Mesh
    Mug_Fourth_Raycaster_Hover: THREE.Mesh
    X_Fourth_Raycaster_Pointer_Hover: THREE.Mesh
    Cactus_Raycaster_Fourth_Hover: THREE.Mesh
    Calender: THREE.Mesh
    Flower_4_Fourth_Hover_Raycaster: THREE.Mesh
    Flower_5_Fourth_Hover_Raycaster: THREE.Mesh
    Microphone_Hover_Fourth_Raycaster: THREE.Mesh
    Frame_1_Second_Raycaster_Hover: THREE.Mesh
    Frame_2_Second_Raycaster_Hover: THREE.Mesh
    Frame_3_Second_Raycaster_Hover: THREE.Mesh
    Flower_1_Fourth_Hover_Raycaster: THREE.Mesh
    Flower_2_Fourth_Hover_Raycaster: THREE.Mesh
    Flower_3_Fourth_Hover_Raycaster: THREE.Mesh
    Pencil_1_Fourth_Hover_Raycaster: THREE.Mesh
    Pencil_2_Fourth_Hover_Raycaster: THREE.Mesh
    Pencil_3_Fourth_Hover_Raycaster: THREE.Mesh
    Pencil_4_Fourth_Hover_Raycaster: THREE.Mesh
    Pencil_5_Fourth_Hover_Raycaster: THREE.Mesh
    Hanging_Plank_2_Third: THREE.Mesh
    About_Button_Third: THREE.Mesh
    Contact_Button_Third: THREE.Mesh
    My_Work_Button_Third: THREE.Mesh
    First: THREE.Mesh
    Second: THREE.Mesh
    Third: THREE.Mesh
    Fourth: THREE.Mesh
    PS5_Digital_stand: THREE.Mesh
    Cat_Second: THREE.SkinnedMesh
    root_1: THREE.Bone
    Bone001: THREE.Bone
    neck: THREE.Bone
    Bone009: THREE.Bone
    earR: THREE.Bone
    earR001: THREE.Bone
    earR002: THREE.Bone
    earL: THREE.Bone
    earL001: THREE.Bone
    earL002: THREE.Bone
    Bone002: THREE.Bone
    Bone003: THREE.Bone
    Bone004: THREE.Bone
    Bone008: THREE.Bone
    Bone005: THREE.Bone
    Bone010: THREE.Bone
    Bone006: THREE.Bone
    Bone011: THREE.Bone
    Bone007: THREE.Bone
    Bone012: THREE.Bone
  }
  materials: {}
}

export interface HoverSettings {
  items?: string[];
  scale: number;
  duration: number;
  rotateX?: number;
  rotateY?: number;
  moveY?: number;
  type?: string;
}
