import * as THREE from "three";
import { GLTF } from "three-stdlib";

export type GLTFResult = GLTF & {
  nodes: {
    Case_Glass: THREE.Mesh
    screen_2: THREE.Mesh
    screen_3: THREE.Mesh
    screen_1: THREE.Mesh
    ['fish-glass']: THREE.Mesh
    ['fish-water']: THREE.Mesh
    ['water-mug']: THREE.Mesh
    Frame_3_Third_Raycaster_Hover: THREE.Mesh
    Frame_2_Third_Raycaster_Hover: THREE.Mesh
    Frame_1_Third_Raycaster_Hover: THREE.Mesh
    ['poster-1']: THREE.Mesh
    Chair_Second_Raycaster_Hover: THREE.Mesh
    About_Button_Second_Raycaster_Pointer_Hover: THREE.Mesh
    Contact_Button_Second_Raycaster_Pointer_Hover: THREE.Mesh
    Microphone_Hover_ٍSecond_Raycaster: THREE.Mesh
    Seaweed_1_Hover_Second_Raycaster: THREE.Mesh
    Seaweed_2_Hover_Second_Raycaster: THREE.Mesh
    Seaweed_3_Hover_Second_Raycaster: THREE.Mesh
    Seaweed_4_Hover_Second_Raycaster: THREE.Mesh
    Seaweed_5_Hover_Second_Raycaster: THREE.Mesh
    Seaweed_6_Hover_Second_Raycaster: THREE.Mesh
    Seaweed_7_Hover_Second_Raycaster: THREE.Mesh
    Seaweed_8_Hover_Second_Raycaster: THREE.Mesh
    Seaweed_9_Hover_Second_Raycaster: THREE.Mesh
    Seaweed_10_Hover_Second_Raycaster: THREE.Mesh
    Seaweed_11_Hover_Second_Raycaster: THREE.Mesh
    Seaweed_12_Hover_Second_Raycaster: THREE.Mesh
    Rock_2_Second_Raycaster_Hover: THREE.Mesh
    Rock_6_Second_Raycaster_Hover: THREE.Mesh
    Rock_1_Second_Raycaster_Hover: THREE.Mesh
    Rock_3_Second_Raycaster_Hover: THREE.Mesh
    Rock_7_Second_Raycaster_Hover: THREE.Mesh
    Rock_4_Second_Raycaster_Hover: THREE.Mesh
    Rock_5_Second_Raycaster_Hover: THREE.Mesh
    Hanging_Plank_2_Second: THREE.Mesh
    Hanging_Plank_1_Second: THREE.Mesh
    My_Work_Button_Second_Raycaster_Pointer_Hover: THREE.Mesh
    Name_Platform_Fourth: THREE.Mesh
    Box_1_Hover_Fourth_Raycaster: THREE.Mesh
    Box_2_Hover_Fourth_Raycaster: THREE.Mesh
    Box_3_Hover_Fourth_Raycaster: THREE.Mesh
    Flower_Basket_Raycaster_Hover_Fourth: THREE.Mesh
    Name_Letter_1_Fourth_Raycaster_Hover: THREE.Mesh
    Name_Letter_2_Fourth_Raycaster_Hover: THREE.Mesh
    Name_Letter_3_Fourth_Raycaster_Hover: THREE.Mesh
    Name_Letter_4_Fourth_Raycaster_Hover: THREE.Mesh
    Name_Letter_5_Fourth_Raycaster_Hover: THREE.Mesh
    Name_Letter_6_Fourth_Raycaster_Hover: THREE.Mesh
    Name_Letter_7_Fourth_Raycaster_Hover: THREE.Mesh
    Name_Letter_8_Fourth_Raycaster_Hover: THREE.Mesh
    Name_Letter_9_Fourth_Raycaster_Hover: THREE.Mesh
    Name_Letter_10_Fourth_Raycaster_Hover: THREE.Mesh
    Name_Letter_11_Fourth_Raycaster_Hover: THREE.Mesh
    Name_Letter_12_Fourth_Raycaster_Hover: THREE.Mesh
    Bulb_1_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_2_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_3_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_4_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_5_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_6_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_7_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_8_Fourth_Raycaster_Hover_2: THREE.Mesh
    Bulb_9_Fourth_Raycaster_Hover_2: THREE.Mesh
    Computer_Fan_1_Fourth_Raycaster: THREE.Mesh
    Computer_Fan_2_Fourth_Raycaster: THREE.Mesh
    Computer_Fan_3_Fourth_Raycaster: THREE.Mesh
    Computer_Fan_4_Fourth_Raycaster: THREE.Mesh
    Computer_Fan_5_Fourth_Raycaster: THREE.Mesh
    ['A#1_Key_Pointer_Raycaster_Second']: THREE.Mesh
    ['A#2_Key_Pointer_Raycaster_Second']: THREE.Mesh
    A1_Key_Pointer_Raycaster_Second: THREE.Mesh
    A2_Key_Pointer_Raycaster_Second: THREE.Mesh
    B1_Key_Pointer_Raycaster_Second: THREE.Mesh
    B2_Key_Pointer_Raycaster_Second: THREE.Mesh
    ['C#1_Key_Pointer_Raycaster_Second']: THREE.Mesh
    ['C#2_Key_Pointer_Raycaster_Second']: THREE.Mesh
    C1_Key_Pointer_Raycaster_Second: THREE.Mesh
    C2_Key_Pointer_Raycaster_Second: THREE.Mesh
    ['D#1_Key_Pointer_Raycaster_Second']: THREE.Mesh
    ['D#2_Key_Pointer_Raycaster_Second']: THREE.Mesh
    D1_Key_Pointer_Raycaster_Second: THREE.Mesh
    D2_Key_Pointer_Raycaster_Second: THREE.Mesh
    E1_Key_Pointer_Raycaster_Second: THREE.Mesh
    E2_Key_Pointer_Raycaster_Second: THREE.Mesh
    ['F#1_Key_Pointer_Raycaster_Second']: THREE.Mesh
    ['F#2_Key_Pointer_Raycaster_Second']: THREE.Mesh
    F1_Key_Pointer_Raycaster_Second: THREE.Mesh
    F2_Key_Pointer_Raycaster_Second: THREE.Mesh
    ['G#1_Key_Pointer_Raycaster_Second']: THREE.Mesh
    ['G#2_Key_Pointer_Raycaster_Second']: THREE.Mesh
    G1_Key_Pointer_Raycaster_Second: THREE.Mesh
    G2_Key_Pointer_Raycaster_Second: THREE.Mesh
    Flower_1_Fourth_Hover_Raycaster: THREE.Mesh
    Flower_2_Fourth_Hover_Raycaster: THREE.Mesh
    Flower_3_Fourth_Hover_Raycaster: THREE.Mesh
    Flower_4_Fourth_Hover_Raycaster: THREE.Mesh
    Flower_5_Fourth_Hover_Raycaster: THREE.Mesh
    Github_Fourth_Raycaster_Pointer_Hover: THREE.Mesh
    Linkedin_Fourth_Raycaster_Pointer_Hover: THREE.Mesh
    X_Fourth_Raycaster_Pointer_Hover: THREE.Mesh
    Pencil_1_Fourth_Hover_Raycaster: THREE.Mesh
    Pencil_2_Fourth_Hover_Raycaster: THREE.Mesh
    Pencil_3_Fourth_Hover_Raycaster: THREE.Mesh
    Pencil_4_Fourth_Hover_Raycaster: THREE.Mesh
    Pencil_5_Fourth_Hover_Raycaster: THREE.Mesh
    ['Bird-Father-Fourth_Raycaster_Hover']: THREE.Mesh
    ['Bird-Son-Fourth_Raycaster_Hover']: THREE.Mesh
    Boba_Plushie_Fourth_Raycaster_Hover: THREE.Mesh
    Egg_1_Fourth_Hover_Raycaster: THREE.Mesh
    Egg_2_Fourth_Hover_Raycaster: THREE.Mesh
    Egg_3_Fourth_Hover_Raycaster: THREE.Mesh
    Cactus_Raycaster_Fourth_Hover: THREE.Mesh
    Hour_Hand_First: THREE.Mesh
    Minute_Hand_First: THREE.Mesh
    Bear_Fourth_Hover_Raycaster: THREE.Mesh
    Bear_Fourth_Hover_Raycaster001: THREE.Mesh
    Cam_Fourth_Raycaster_Hover: THREE.Mesh
    Coffee_Mug_Fourth_Raycaster_Hover: THREE.Mesh
    Dot_1_Raycaster_Hover_Fourth: THREE.Mesh
    Dot_2_Raycaster_Hover_Fourth: THREE.Mesh
    Dot_3_Raycaster_Hover_Fourth: THREE.Mesh
    Drawer_Raycaster_Hover_Fourth: THREE.Mesh
    Duck_Father_Fourth_Hover_Raycaster: THREE.Mesh
    Duck_Son_Fourth_Hover_Raycaster001: THREE.Mesh
    Evee_Raycaster_Hover_Fourth: THREE.Mesh
    Fish_Fourth_Hover_Raycaster: THREE.Mesh
    Keyboard_Raycaster_Hover_Fourth: THREE.Mesh
    Kitten_Raycaster_Hover_Fourth: THREE.Mesh
    Mouse_Raycaster_Hover_Fourth: THREE.Mesh
    Note_Raycaster_Hover_Fourth: THREE.Mesh
    Pen_Raycaster_Hover_Fourth: THREE.Mesh
    Puppy_Raycaster_Hover_Fourth: THREE.Mesh
    Slipper_1_Fourth_Hover_Raycaster: THREE.Mesh
    Slipper_2_Fourth_Hover_Raycaster: THREE.Mesh
    Frame_1: THREE.Mesh
    Frame_2: THREE.Mesh
    Frame_3: THREE.Mesh
    First: THREE.Mesh
    second: THREE.Mesh
    third: THREE.Mesh
    fourth: THREE.Mesh
    Cat_Third_Raycaster_Hover: THREE.SkinnedMesh
    root_1: THREE.Bone
    Bone001: THREE.Bone
    neck: THREE.Bone
    head: THREE.Bone
    earR: THREE.Bone
    earR001: THREE.Bone
    earR002: THREE.Bone
    earL: THREE.Bone
    earL001: THREE.Bone
    earL002: THREE.Bone
    ['Tail-1']: THREE.Bone
    ['Tail-2']: THREE.Bone
    ['Tail-3']: THREE.Bone
    ['Tail-4']: THREE.Bone
    ['Tail-5']: THREE.Bone
    ['Tail-6']: THREE.Bone
    ['Tail-7']: THREE.Bone
    ['Tail-8']: THREE.Bone
    ['Tail-9']: THREE.Bone
    ['Tail-10']: THREE.Bone
  }
  materials: {}
}
