import * as THREE from "three";
import { JSX, useLayoutEffect, useMemo } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { GLTFResult } from "@/types/room.types";
import { useRoomTextures } from "@/hooks/useRoomTextures";
import { CinematicMaterial } from "@/components/CinematicMaterial";

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { scene } = useGLTF("/models/my-room-3d.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(clone) as unknown as GLTFResult;

  const textures = useRoomTextures();

  const isDay = true; // Replace with your actual logic to determine day/night

  useLayoutEffect(() => {
    Object.entries(nodes).forEach(([name, node]) => {
      if (node instanceof THREE.Mesh) {
        Object.entries(textures).forEach(([key, textureGroup]) => {
          if (name.includes(key)) {
            if (node.material) {
              (node.material as THREE.MeshBasicMaterial).dispose();
            }
            node.material = new THREE.MeshBasicMaterial({
              map: isDay ? textureGroup.day : textureGroup.night,
            });
          }
        });
      }
    });
  }, [nodes, textures, isDay]);

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Case_Glass"
        geometry={nodes.Case_Glass.geometry}
        material={nodes.Case_Glass.material}
      />
      <mesh
        name="screen_2"
        geometry={nodes.screen_2.geometry}
        material={nodes.screen_2.material}
      />
      <mesh
        name="screen_3"
        geometry={nodes.screen_3.geometry}
        material={nodes.screen_3.material}
      />
      <mesh
        name="screen_1"
        geometry={nodes.screen_1.geometry}
        material={nodes.screen_1.material}
      />
      <mesh
        name="fish-glass"
        geometry={nodes["fish-glass"].geometry}
        material={nodes["fish-glass"].material}
      />
      <mesh
        name="fish-water"
        geometry={nodes["fish-water"].geometry}
        material={nodes["fish-water"].material}
      />
      <mesh
        name="water-mug"
        geometry={nodes["water-mug"].geometry}
        material={nodes["water-mug"].material}
      />
      <mesh
        name="Frame_3_Third_Raycaster_Hover"
        geometry={nodes.Frame_3_Third_Raycaster_Hover.geometry}
        material={nodes.Frame_3_Third_Raycaster_Hover.material}
      />
      <mesh
        name="Frame_2_Third_Raycaster_Hover"
        geometry={nodes.Frame_2_Third_Raycaster_Hover.geometry}
        material={nodes.Frame_2_Third_Raycaster_Hover.material}
      />
      <mesh
        name="Frame_1_Third_Raycaster_Hover"
        geometry={nodes.Frame_1_Third_Raycaster_Hover.geometry}
        material={nodes.Frame_1_Third_Raycaster_Hover.material}
      />
      <mesh
        name="poster-1"
        geometry={nodes["poster-1"].geometry}
        material={nodes["poster-1"].material}
      />
      <mesh
        name="Chair_Second_Raycaster_Hover"
        geometry={nodes.Chair_Second_Raycaster_Hover.geometry}
        material={nodes.Chair_Second_Raycaster_Hover.material}
      />
      <mesh
        name="About_Button_Second_Raycaster_Pointer_Hover"
        geometry={nodes.About_Button_Second_Raycaster_Pointer_Hover.geometry}
        material={nodes.About_Button_Second_Raycaster_Pointer_Hover.material}
      />
      <mesh
        name="Contact_Button_Second_Raycaster_Pointer_Hover"
        geometry={nodes.Contact_Button_Second_Raycaster_Pointer_Hover.geometry}
        material={nodes.Contact_Button_Second_Raycaster_Pointer_Hover.material}
      />
      <mesh
        name="Microphone_Hover_ٍSecond_Raycaster"
        geometry={nodes.Microphone_Hover_ٍSecond_Raycaster.geometry}
        material={nodes.Microphone_Hover_ٍSecond_Raycaster.material}
      />
      <mesh
        name="Seaweed_1_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_1_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_1_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Seaweed_2_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_2_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_2_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Seaweed_3_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_3_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_3_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Seaweed_4_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_4_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_4_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Seaweed_5_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_5_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_5_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Seaweed_6_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_6_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_6_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Seaweed_7_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_7_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_7_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Seaweed_8_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_8_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_8_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Seaweed_9_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_9_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_9_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Seaweed_10_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_10_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_10_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Seaweed_11_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_11_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_11_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Seaweed_12_Hover_Second_Raycaster"
        geometry={nodes.Seaweed_12_Hover_Second_Raycaster.geometry}
        material={nodes.Seaweed_12_Hover_Second_Raycaster.material}
      />
      <mesh
        name="Rock_2_Second_Raycaster_Hover"
        geometry={nodes.Rock_2_Second_Raycaster_Hover.geometry}
        material={nodes.Rock_2_Second_Raycaster_Hover.material}
      />
      <mesh
        name="Rock_6_Second_Raycaster_Hover"
        geometry={nodes.Rock_6_Second_Raycaster_Hover.geometry}
        material={nodes.Rock_6_Second_Raycaster_Hover.material}
      />
      <mesh
        name="Rock_1_Second_Raycaster_Hover"
        geometry={nodes.Rock_1_Second_Raycaster_Hover.geometry}
        material={nodes.Rock_1_Second_Raycaster_Hover.material}
      />
      <mesh
        name="Rock_3_Second_Raycaster_Hover"
        geometry={nodes.Rock_3_Second_Raycaster_Hover.geometry}
        material={nodes.Rock_3_Second_Raycaster_Hover.material}
      />
      <mesh
        name="Rock_7_Second_Raycaster_Hover"
        geometry={nodes.Rock_7_Second_Raycaster_Hover.geometry}
        material={nodes.Rock_7_Second_Raycaster_Hover.material}
      />
      <mesh
        name="Rock_4_Second_Raycaster_Hover"
        geometry={nodes.Rock_4_Second_Raycaster_Hover.geometry}
        material={nodes.Rock_4_Second_Raycaster_Hover.material}
      />
      <mesh
        name="Rock_5_Second_Raycaster_Hover"
        geometry={nodes.Rock_5_Second_Raycaster_Hover.geometry}
        material={nodes.Rock_5_Second_Raycaster_Hover.material}
      />
      <mesh
        name="Hanging_Plank_2_Second"
        geometry={nodes.Hanging_Plank_2_Second.geometry}
        material={nodes.Hanging_Plank_2_Second.material}
      />
      <mesh
        name="Hanging_Plank_1_Second"
        geometry={nodes.Hanging_Plank_1_Second.geometry}
        material={nodes.Hanging_Plank_1_Second.material}
      />
      <mesh
        name="My_Work_Button_Second_Raycaster_Pointer_Hover"
        geometry={nodes.My_Work_Button_Second_Raycaster_Pointer_Hover.geometry}
        material={nodes.My_Work_Button_Second_Raycaster_Pointer_Hover.material}
      />
      <mesh
        name="Name_Platform_Fourth"
        geometry={nodes.Name_Platform_Fourth.geometry}
        material={nodes.Name_Platform_Fourth.material}
      />
      <mesh
        name="Box_1_Hover_Fourth_Raycaster"
        geometry={nodes.Box_1_Hover_Fourth_Raycaster.geometry}
        material={nodes.Box_1_Hover_Fourth_Raycaster.material}
      />
      <mesh
        name="Box_2_Hover_Fourth_Raycaster"
        geometry={nodes.Box_2_Hover_Fourth_Raycaster.geometry}
        material={nodes.Box_2_Hover_Fourth_Raycaster.material}
      />
      <mesh
        name="Box_3_Hover_Fourth_Raycaster"
        geometry={nodes.Box_3_Hover_Fourth_Raycaster.geometry}
        material={nodes.Box_3_Hover_Fourth_Raycaster.material}
      />
      <mesh
        name="Flower_Basket_Raycaster_Hover_Fourth"
        geometry={nodes.Flower_Basket_Raycaster_Hover_Fourth.geometry}
        material={nodes.Flower_Basket_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Name_Letter_1_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_1_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_1_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Name_Letter_2_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_2_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_2_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Name_Letter_3_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_3_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_3_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Name_Letter_4_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_4_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_4_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Name_Letter_5_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_5_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_5_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Name_Letter_6_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_6_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_6_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Name_Letter_7_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_7_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_7_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Name_Letter_8_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_8_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_8_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Name_Letter_9_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_9_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_9_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Name_Letter_10_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_10_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_10_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Name_Letter_11_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_11_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_11_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Name_Letter_12_Fourth_Raycaster_Hover"
        geometry={nodes.Name_Letter_12_Fourth_Raycaster_Hover.geometry}
        material={nodes.Name_Letter_12_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Bulb_1_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_1_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_1_Fourth_Raycaster_Hover_2.material}
      />
      <mesh
        name="Bulb_2_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_2_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_2_Fourth_Raycaster_Hover_2.material}
      />
      <mesh
        name="Bulb_3_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_3_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_3_Fourth_Raycaster_Hover_2.material}
      />
      <mesh
        name="Bulb_4_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_4_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_4_Fourth_Raycaster_Hover_2.material}
      />
      <mesh
        name="Bulb_5_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_5_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_5_Fourth_Raycaster_Hover_2.material}
      />
      <mesh
        name="Bulb_6_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_6_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_6_Fourth_Raycaster_Hover_2.material}
      />
      <mesh
        name="Bulb_7_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_7_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_7_Fourth_Raycaster_Hover_2.material}
      />
      <mesh
        name="Bulb_8_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_8_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_8_Fourth_Raycaster_Hover_2.material}
      />
      <mesh
        name="Bulb_9_Fourth_Raycaster_Hover_2"
        geometry={nodes.Bulb_9_Fourth_Raycaster_Hover_2.geometry}
        material={nodes.Bulb_9_Fourth_Raycaster_Hover_2.material}
      />
      <mesh
        name="Computer_Fan_1_Fourth_Raycaster"
        geometry={nodes.Computer_Fan_1_Fourth_Raycaster.geometry}
        material={nodes.Computer_Fan_1_Fourth_Raycaster.material}
      />
      <mesh
        name="Computer_Fan_2_Fourth_Raycaster"
        geometry={nodes.Computer_Fan_2_Fourth_Raycaster.geometry}
        material={nodes.Computer_Fan_2_Fourth_Raycaster.material}
      />
      <mesh
        name="Computer_Fan_3_Fourth_Raycaster"
        geometry={nodes.Computer_Fan_3_Fourth_Raycaster.geometry}
        material={nodes.Computer_Fan_3_Fourth_Raycaster.material}
      />
      <mesh
        name="Computer_Fan_4_Fourth_Raycaster"
        geometry={nodes.Computer_Fan_4_Fourth_Raycaster.geometry}
        material={nodes.Computer_Fan_4_Fourth_Raycaster.material}
      />
      <mesh
        name="Computer_Fan_5_Fourth_Raycaster"
        geometry={nodes.Computer_Fan_5_Fourth_Raycaster.geometry}
        material={nodes.Computer_Fan_5_Fourth_Raycaster.material}
      />
      <mesh
        name="A#1_Key_Pointer_Raycaster_Second"
        geometry={nodes["A#1_Key_Pointer_Raycaster_Second"].geometry}
        material={nodes["A#1_Key_Pointer_Raycaster_Second"].material}
      />
      <mesh
        name="A#2_Key_Pointer_Raycaster_Second"
        geometry={nodes["A#2_Key_Pointer_Raycaster_Second"].geometry}
        material={nodes["A#2_Key_Pointer_Raycaster_Second"].material}
      />
      <mesh
        name="A1_Key_Pointer_Raycaster_Second"
        geometry={nodes.A1_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.A1_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="A2_Key_Pointer_Raycaster_Second"
        geometry={nodes.A2_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.A2_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="B1_Key_Pointer_Raycaster_Second"
        geometry={nodes.B1_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.B1_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="B2_Key_Pointer_Raycaster_Second"
        geometry={nodes.B2_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.B2_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="C#1_Key_Pointer_Raycaster_Second"
        geometry={nodes["C#1_Key_Pointer_Raycaster_Second"].geometry}
        material={nodes["C#1_Key_Pointer_Raycaster_Second"].material}
      />
      <mesh
        name="C#2_Key_Pointer_Raycaster_Second"
        geometry={nodes["C#2_Key_Pointer_Raycaster_Second"].geometry}
        material={nodes["C#2_Key_Pointer_Raycaster_Second"].material}
      />
      <mesh
        name="C1_Key_Pointer_Raycaster_Second"
        geometry={nodes.C1_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.C1_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="C2_Key_Pointer_Raycaster_Second"
        geometry={nodes.C2_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.C2_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="D#1_Key_Pointer_Raycaster_Second"
        geometry={nodes["D#1_Key_Pointer_Raycaster_Second"].geometry}
        material={nodes["D#1_Key_Pointer_Raycaster_Second"].material}
      />
      <mesh
        name="D#2_Key_Pointer_Raycaster_Second"
        geometry={nodes["D#2_Key_Pointer_Raycaster_Second"].geometry}
        material={nodes["D#2_Key_Pointer_Raycaster_Second"].material}
      />
      <mesh
        name="D1_Key_Pointer_Raycaster_Second"
        geometry={nodes.D1_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.D1_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="D2_Key_Pointer_Raycaster_Second"
        geometry={nodes.D2_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.D2_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="E1_Key_Pointer_Raycaster_Second"
        geometry={nodes.E1_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.E1_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="E2_Key_Pointer_Raycaster_Second"
        geometry={nodes.E2_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.E2_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="F#1_Key_Pointer_Raycaster_Second"
        geometry={nodes["F#1_Key_Pointer_Raycaster_Second"].geometry}
        material={nodes["F#1_Key_Pointer_Raycaster_Second"].material}
      />
      <mesh
        name="F#2_Key_Pointer_Raycaster_Second"
        geometry={nodes["F#2_Key_Pointer_Raycaster_Second"].geometry}
        material={nodes["F#2_Key_Pointer_Raycaster_Second"].material}
      />
      <mesh
        name="F1_Key_Pointer_Raycaster_Second"
        geometry={nodes.F1_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.F1_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="F2_Key_Pointer_Raycaster_Second"
        geometry={nodes.F2_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.F2_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="G#1_Key_Pointer_Raycaster_Second"
        geometry={nodes["G#1_Key_Pointer_Raycaster_Second"].geometry}
        material={nodes["G#1_Key_Pointer_Raycaster_Second"].material}
      />
      <mesh
        name="G#2_Key_Pointer_Raycaster_Second"
        geometry={nodes["G#2_Key_Pointer_Raycaster_Second"].geometry}
        material={nodes["G#2_Key_Pointer_Raycaster_Second"].material}
      />
      <mesh
        name="G1_Key_Pointer_Raycaster_Second"
        geometry={nodes.G1_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.G1_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="G2_Key_Pointer_Raycaster_Second"
        geometry={nodes.G2_Key_Pointer_Raycaster_Second.geometry}
        material={nodes.G2_Key_Pointer_Raycaster_Second.material}
      />
      <mesh
        name="Flower_1_Fourth_Hover_Raycaster"
        geometry={nodes.Flower_1_Fourth_Hover_Raycaster.geometry}
        material={nodes.Flower_1_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Flower_2_Fourth_Hover_Raycaster"
        geometry={nodes.Flower_2_Fourth_Hover_Raycaster.geometry}
        material={nodes.Flower_2_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Flower_3_Fourth_Hover_Raycaster"
        geometry={nodes.Flower_3_Fourth_Hover_Raycaster.geometry}
        material={nodes.Flower_3_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Flower_4_Fourth_Hover_Raycaster"
        geometry={nodes.Flower_4_Fourth_Hover_Raycaster.geometry}
        material={nodes.Flower_4_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Flower_5_Fourth_Hover_Raycaster"
        geometry={nodes.Flower_5_Fourth_Hover_Raycaster.geometry}
        material={nodes.Flower_5_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Github_Fourth_Raycaster_Pointer_Hover"
        geometry={nodes.Github_Fourth_Raycaster_Pointer_Hover.geometry}
        material={nodes.Github_Fourth_Raycaster_Pointer_Hover.material}
      />
      <mesh
        name="Linkedin_Fourth_Raycaster_Pointer_Hover"
        geometry={nodes.Linkedin_Fourth_Raycaster_Pointer_Hover.geometry}
        material={nodes.Linkedin_Fourth_Raycaster_Pointer_Hover.material}
      />
      <mesh
        name="X_Fourth_Raycaster_Pointer_Hover"
        geometry={nodes.X_Fourth_Raycaster_Pointer_Hover.geometry}
        material={nodes.X_Fourth_Raycaster_Pointer_Hover.material}
      />
      <mesh
        name="Pencil_1_Fourth_Hover_Raycaster"
        geometry={nodes.Pencil_1_Fourth_Hover_Raycaster.geometry}
        material={nodes.Pencil_1_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Pencil_2_Fourth_Hover_Raycaster"
        geometry={nodes.Pencil_2_Fourth_Hover_Raycaster.geometry}
        material={nodes.Pencil_2_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Pencil_3_Fourth_Hover_Raycaster"
        geometry={nodes.Pencil_3_Fourth_Hover_Raycaster.geometry}
        material={nodes.Pencil_3_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Pencil_4_Fourth_Hover_Raycaster"
        geometry={nodes.Pencil_4_Fourth_Hover_Raycaster.geometry}
        material={nodes.Pencil_4_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Pencil_5_Fourth_Hover_Raycaster"
        geometry={nodes.Pencil_5_Fourth_Hover_Raycaster.geometry}
        material={nodes.Pencil_5_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Bird-Father-Fourth_Raycaster_Hover"
        geometry={nodes["Bird-Father-Fourth_Raycaster_Hover"].geometry}
        material={nodes["Bird-Father-Fourth_Raycaster_Hover"].material}
      />
      <mesh
        name="Bird-Son-Fourth_Raycaster_Hover"
        geometry={nodes["Bird-Son-Fourth_Raycaster_Hover"].geometry}
        material={nodes["Bird-Son-Fourth_Raycaster_Hover"].material}
      />
      <mesh
        name="Boba_Plushie_Fourth_Raycaster_Hover"
        geometry={nodes.Boba_Plushie_Fourth_Raycaster_Hover.geometry}
        material={nodes.Boba_Plushie_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Egg_1_Fourth_Hover_Raycaster"
        geometry={nodes.Egg_1_Fourth_Hover_Raycaster.geometry}
        material={nodes.Egg_1_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Egg_2_Fourth_Hover_Raycaster"
        geometry={nodes.Egg_2_Fourth_Hover_Raycaster.geometry}
        material={nodes.Egg_2_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Egg_3_Fourth_Hover_Raycaster"
        geometry={nodes.Egg_3_Fourth_Hover_Raycaster.geometry}
        material={nodes.Egg_3_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Cactus_Raycaster_Fourth_Hover"
        geometry={nodes.Cactus_Raycaster_Fourth_Hover.geometry}
        material={nodes.Cactus_Raycaster_Fourth_Hover.material}
      />
      <mesh
        name="Hour_Hand_First"
        geometry={nodes.Hour_Hand_First.geometry}
        material={nodes.Hour_Hand_First.material}
      />
      <mesh
        name="Minute_Hand_First"
        geometry={nodes.Minute_Hand_First.geometry}
        material={nodes.Minute_Hand_First.material}
      />
      <mesh
        name="Bear_Fourth_Hover_Raycaster"
        geometry={nodes.Bear_Fourth_Hover_Raycaster.geometry}
        material={nodes.Bear_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Bear_Fourth_Hover_Raycaster001"
        geometry={nodes.Bear_Fourth_Hover_Raycaster001.geometry}
        material={nodes.Bear_Fourth_Hover_Raycaster001.material}
      />
      <mesh
        name="Cam_Fourth_Raycaster_Hover"
        geometry={nodes.Cam_Fourth_Raycaster_Hover.geometry}
        material={nodes.Cam_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Coffee_Mug_Fourth_Raycaster_Hover"
        geometry={nodes.Coffee_Mug_Fourth_Raycaster_Hover.geometry}
        material={nodes.Coffee_Mug_Fourth_Raycaster_Hover.material}
      />
      <mesh
        name="Dot_1_Raycaster_Hover_Fourth"
        geometry={nodes.Dot_1_Raycaster_Hover_Fourth.geometry}
        material={nodes.Dot_1_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Dot_2_Raycaster_Hover_Fourth"
        geometry={nodes.Dot_2_Raycaster_Hover_Fourth.geometry}
        material={nodes.Dot_2_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Dot_3_Raycaster_Hover_Fourth"
        geometry={nodes.Dot_3_Raycaster_Hover_Fourth.geometry}
        material={nodes.Dot_3_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Drawer_Raycaster_Hover_Fourth"
        geometry={nodes.Drawer_Raycaster_Hover_Fourth.geometry}
        material={nodes.Drawer_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Duck_Father_Fourth_Hover_Raycaster"
        geometry={nodes.Duck_Father_Fourth_Hover_Raycaster.geometry}
        material={nodes.Duck_Father_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Duck_Son_Fourth_Hover_Raycaster001"
        geometry={nodes.Duck_Son_Fourth_Hover_Raycaster001.geometry}
        material={nodes.Duck_Son_Fourth_Hover_Raycaster001.material}
      />
      <mesh
        name="Evee_Raycaster_Hover_Fourth"
        geometry={nodes.Evee_Raycaster_Hover_Fourth.geometry}
        material={nodes.Evee_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Fish_Fourth_Hover_Raycaster"
        geometry={nodes.Fish_Fourth_Hover_Raycaster.geometry}
        material={nodes.Fish_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Keyboard_Raycaster_Hover_Fourth"
        geometry={nodes.Keyboard_Raycaster_Hover_Fourth.geometry}
        material={nodes.Keyboard_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Kitten_Raycaster_Hover_Fourth"
        geometry={nodes.Kitten_Raycaster_Hover_Fourth.geometry}
        material={nodes.Kitten_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Mouse_Raycaster_Hover_Fourth"
        geometry={nodes.Mouse_Raycaster_Hover_Fourth.geometry}
        material={nodes.Mouse_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Note_Raycaster_Hover_Fourth"
        geometry={nodes.Note_Raycaster_Hover_Fourth.geometry}
        material={nodes.Note_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Pen_Raycaster_Hover_Fourth"
        geometry={nodes.Pen_Raycaster_Hover_Fourth.geometry}
        material={nodes.Pen_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Puppy_Raycaster_Hover_Fourth"
        geometry={nodes.Puppy_Raycaster_Hover_Fourth.geometry}
        material={nodes.Puppy_Raycaster_Hover_Fourth.material}
      />
      <mesh
        name="Slipper_1_Fourth_Hover_Raycaster"
        geometry={nodes.Slipper_1_Fourth_Hover_Raycaster.geometry}
        material={nodes.Slipper_1_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Slipper_2_Fourth_Hover_Raycaster"
        geometry={nodes.Slipper_2_Fourth_Hover_Raycaster.geometry}
        material={nodes.Slipper_2_Fourth_Hover_Raycaster.material}
      />
      <mesh
        name="Frame_1"
        geometry={nodes.Frame_1.geometry}
        material={nodes.Frame_1.material}
      />
      <mesh
        name="Frame_2"
        geometry={nodes.Frame_2.geometry}
        material={nodes.Frame_2.material}
      />
      <mesh
        name="Frame_3"
        geometry={nodes.Frame_3.geometry}
        material={nodes.Frame_3.material}
      />
      <mesh
        name="First"
        geometry={nodes.First.geometry}
        material={nodes.First.material}
      />
      <mesh
        name="second"
        geometry={nodes.second.geometry}
        material={nodes.second.material}
      />
      <mesh
        name="third"
        geometry={nodes.third.geometry}
        material={nodes.third.material}
      />
      <mesh
        name="fourth"
        geometry={nodes.fourth.geometry}
        material={nodes.fourth.material}
      />
      <skinnedMesh
        name="Cat_Third_Raycaster_Hover"
        geometry={nodes.Cat_Third_Raycaster_Hover.geometry}
        material={nodes.Cat_Third_Raycaster_Hover.material}
        skeleton={nodes.Cat_Third_Raycaster_Hover.skeleton}
        morphTargetDictionary={
          nodes.Cat_Third_Raycaster_Hover.morphTargetDictionary
        }
        morphTargetInfluences={
          nodes.Cat_Third_Raycaster_Hover.morphTargetInfluences
        }
      />
      <primitive object={nodes.root_1} />
      <primitive object={nodes.Bone001} />
      <primitive object={nodes.neck} />
      <primitive object={nodes.head} />
      <primitive object={nodes.earR} />
      <primitive object={nodes.earR001} />
      <primitive object={nodes.earR002} />
      <primitive object={nodes.earL} />
      <primitive object={nodes.earL001} />
      <primitive object={nodes.earL002} />
      <primitive object={nodes["Tail-1"]} />
      <primitive object={nodes["Tail-2"]} />
      <primitive object={nodes["Tail-3"]} />
      <primitive object={nodes["Tail-4"]} />
      <primitive object={nodes["Tail-5"]} />
      <primitive object={nodes["Tail-6"]} />
      <primitive object={nodes["Tail-7"]} />
      <primitive object={nodes["Tail-8"]} />
      <primitive object={nodes["Tail-9"]} />
      <primitive object={nodes["Tail-10"]} />
    </group>
  );
}

useGLTF.preload("/models/my-room-3d.glb");
