import { HoverSettings } from "@/types/room.types";

export const SUFFIX = "_Third";

export const KEYS = [
  "C1",
  "C#1",
  "D1",
  "D#1",
  "E1",
  "F1",
  "F#1",
  "G1",
  "G#1",
  "A1",
  "A#1",
  "B1",
  "C2",
  "C#2",
  "D2",
  "D#2",
  "E2",
  "F2",
  "F#2",
  "G2",
  "G#2",
  "A2",
  "A#2",
  "B2",
];

export const objectsWithIntroAnimations = [
  "Hanging_Plank_1",
  "Hanging_Plank_2",
  "My_Work_Button",
  "About_Button",
  "Contact_Button",
  "Boba",
  "GitHub",
  "LinkedIn",
  "X",
  "Name_Letter_1",
  "Name_Letter_2",
  "Name_Letter_3",
  "Name_Letter_4",
  "Name_Letter_5",
  "Name_Letter_6",
  "Name_Letter_7",
  "Name_Letter_8",
  "Name_Letter_9",
  "Name_Letter_10",
  "Name_Letter_11",
  "Name_Letter_12",
  "Dot_1",
  "Dot_2",
  "Dot_3",
  "Flower_1",
  "Flower_2",
  "Flower_3",
  "Flower_4",
  "Flower_5",
  "Box_1",
  "Box_2",
  "Box_3",
  "Lamp",
  "Slipper_1",
  "Slipper_2",
  "Fish_Second",
  "Egg_1",
  "Egg_2",
  "Egg_3",
  "Frame_1",
  "Frame_2",
  "Frame_3",
  "C1",
  "C#1",
  "D1",
  "D#1",
  "E1",
  "F1",
  "F#1",
  "G1",
  "G#1",
  "A1",
  "A#1",
  "B1",
  "C2",
  "C#2",
  "D2",
  "D#2",
  "E2",
  "F2",
  "F#2",
  "G2",
  "G#2",
  "A2",
  "A#2",
  "B2",
];

export const objectsWithHoverAnimations = [
  "My_Work_Button",
  "About_Button",
  "Contact_Button",
  "Boba",
  "GitHub",
  "LinkedIn",
  "X",
  "Name_Letter_1",
  "Name_Letter_2",
  "Name_Letter_3",
  "Name_Letter_4",
  "Name_Letter_5",
  "Name_Letter_6",
  "Name_Letter_7",
  "Name_Letter_8",
  "Name_Letter_9",
  "Name_Letter_10",
  "Name_Letter_11",
  "Name_Letter_12",
  "Dot_1",
  "Dot_2",
  "Dot_3",
  "Flower_1",
  "Flower_2",
  "Flower_3",
  "Flower_4",
  "Flower_5",
  "Box_1",
  "Box_2",
  "Box_3",
  "Lamp",
  "Slipper_1",
  "Slipper_2",
  "Fish_Second",
  "Egg_1",
  "Egg_2",
  "Egg_3",
  "Frame_1",
  "Frame_2",
  "Frame_3",
  "Rock_1",
  "Rock_2",
  "Rock_3",
  "Rock_4",
  "Rock_5",
  "Rock_6",
  "Rock_7",
  "Seaweed_1",
  "Seaweed_2",
  "Seaweed_3",
  "Seaweed_4",
  "Seaweed_5",
  "Seaweed_6",
  "Seaweed_7",
  "Seaweed_8",
  "Seaweed_9",
  "Seaweed_10",
  "Seaweed_11",
  "Seaweed_12",
  "Bird_Father",
  "Bird_Son",
  "Cam",
  "Duck_Father",
  "Duck_Son",
  "Keyboard",
  "Kitten",
  "Pencil_1",
  "Pencil_2",
  "Pencil_3",
  "Pencil_4",
  "Pencil_5",
  "Puppy",
  "Bulb_1",
  "Bulb_2",
  "Bulb_3",
  "Bulb_4",
  "Bulb_5",
  "Bulb_6",
  "Bulb_7",
  "Bulb_8",
  "Bulb_9",
  "Bear_Father",
  "Bear_Son",
  "Coffee_Mug",
  "Mouth",
  "Cactus",
  "Microphone",
  "Flower_Basket",
  "Evee",
  "Mug_Fourth",
];

export const HOVER_CONFIG: Record<string, HoverSettings> = {
  BUTTONS: {
    items: ["Button", "GitHub", "LinkedIn", "X"],
    scale: 1.2,
    rotateX: Math.PI / 10,
    duration: 0.3,
  },
  FLOATING: {
    items: ["Name_Letter", "Boba", "Dot"],
    scale: 1.2,
    duration: 0.3,
  },
  ANIMALS: {
    items: ["Evee", "Fish", "Bird", "Duck", "Kitten", "Puppy", "Bear"],
    scale: 1.2,
    duration: 0.4,
  },
  FLOWERS: {
    items: ["Flower", "Cactus"],
    scale: 1.25,
    duration: 0.3,
  },
  PENCILS: {
    items: ["Pencil"],
    scale: 1.5,
    moveY: 0.02,
    duration: 0.3,
  },
  BULBS: {
    items: ["Bulb"],
    scale: 1.4,
    duration: 0.4,
  },
  LAMP: {
    items: ["Lamp"],
    scale: 1.2,
    duration: 0.4,
  },
  EGG: {
    items: ["Egg"],
    scale: 1.6,
    moveY: 0.01,
    duration: 0.4,
  },
  NATURE_BG: {
    items: ["Rock", "Seaweed"],
    scale: 1.3,
    duration: 0.3,
  },
  BOX: {
    items: ["Box"],
    scale: 1.2,
    rotateY: -Math.PI / 10,
    duration: 0.3,
  },
  FRAMES: {
    items: ["Frame"],
    scale: 1.2,
    duration: 0.3,
  },
  LETTER: {
    items: ["Name_Letter" , "Dot"],
    scale: 1.4,
    duration: 0.3,
  },
  DEFAULT: {
    scale: 1.2,
    rotateY: -Math.PI / 10,
    duration: 0.4,
  },
};
